//go:build cgo

package main

import (
	"testing"

	http "github.com/bogdanfinn/fhttp"
)

// TestCacheKeyParityWithPython pins buildCacheKeyFromConfig against hash
// vectors generated by tls_client._core._compute_cache_key_hash (Python).
// python_tests/test_cache_key_parity.py holds the same constants on the
// Python side.  If either side drifts, these tests fail BEFORE production
// cache keys diverge and silently poison the client pool.
// Format version: 3 (ABI 2 — disable_session_tickets / tls_keylog_path /
// root_ca_pem / trust_anchors_payload).
func TestCacheKeyParityWithPython(t *testing.T) {
	const testPEM = "-----BEGIN CERTIFICATE-----\nAAE=\n-----END CERTIFICATE-----\n"

	ctc, cleanup := newCustomTlsClientForTest(
		"771,4865-4866-4867,0-23-65281,29-23-24,0", "ABCD", 15663105,
	)
	defer cleanup()

	full := &requestConfig{
		clientIdentifier:      "chrome_133",
		pseudoHeaderOrder:     []string{":method", ":authority", ":scheme", ":path"},
		defaultHeaders:        http.Header{"User-Agent": {"UA1"}},
		timeoutSeconds:        30,
		withRandomTLSExtOrder: true,
		disableSessionTickets: true,
		tlsKeylogPath:         "C:/temp/kl.txt",
		rootCAPEM:             []byte(testPEM),
		h2MaxDataFrameSize:    14000,
		prefacePingIdleMs:     10000,
		hpackIndexingPol:      "chrome",
	}
	const wantFull = "672f67e5996cafe5167bbb50b2c32f76181e19f564fda270e91b67306ac474bc"
	if got := buildCacheKeyFromConfig(full); got != wantFull {
		t.Fatalf("full vector mismatch:\n got  %s\n want %s", got, wantFull)
	}

	minimal := &requestConfig{
		clientIdentifier:      "chrome_133",
		defaultHeaders:        http.Header{"User-Agent": {"UA1"}},
		timeoutSeconds:        30,
		withRandomTLSExtOrder: true,
		customTLSClient:       ctc,
	}
	const wantMinimal = "c5fcb1ed64fbde71a681052e916ccf25e004ef3b537770a44948232da582be5f"
	if got := buildCacheKeyFromConfig(minimal); got != wantMinimal {
		t.Fatalf("minimal vector mismatch:\n got  %s\n want %s", got, wantMinimal)
	}

	// The ABI-2 fields must actually participate in the cache key.
	if buildCacheKeyFromConfig(full) == buildCacheKeyFromConfig(minimal) {
		t.Fatal("ABI 2 fields did not influence the cache key")
	}
}
